### ISSUE TITLE
No name being displayed for attachment in add_event

### ISSUE THREAD

**Issue by abhayraw1** [ncs-jss/benocilaez#3]
The name of the file being uploaded should be displayed in the add event page.

**Comment by Sahilkmaurya** [comment]
issud resolved

**Comment by abhayraw1** [comment]
@Sahilkmaurya The 'choose file' button should not be visible.

**Comment by Sahilkmaurya** [comment]
resolved

**Comment by Sahilkmaurya** [comment]
The name is still not being displayed.

**Comment by Nelabh** [comment]
Issue Resolved with complete frontend and backend implementation
